# -*- coding: utf-8 -*-
"""AlokUntitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lFxMXueQl9hhd8IXdyyRg8WDt6fQRvt
"""

from flask import Flask, request, jsonifyjsonifjsonifyy
!pip install openai

app=Flask(__name__)

import openai

openai.api_key = "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"  # Ganti dengan API key kamu

def chatgpt(prompt):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",  # atau "gpt-4" jika tersedia
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    return response['choices'][0]['message']['content']

@app.route('/')
def index():
    prompt = request.args.get('prompt', 'Tidak ada prompt')
    return chatgpt('prompt','buat suasana ini menjadi adegan cerita')

if __name__=="__main__":
   app.run(debug=True)